#!/usr/bin/env bash

# Store the files temp
OUTPUT_DIR="/tmp/s3-bash-scripts"


mkdir -p $OUTPUT_DIR

NUM_FILES=$((RANDOM %6 + 5))

mkdir -p "$OUTPUT_DIR"

for ((i=1; i<=NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/file_$i.txt"
    
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done