#!/usr/bin/env bash
echo "== sync"

set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "there needs to be a bucket name eg ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# Check for filename prefix
if [ -z "$2" ]; then
    echo "there needs to be a filename prefix eg ./bucket my-bucket-name my-filename-prefix"
    exit 1
fi

FILENAME_PREFIX=$2



# Store the files temp
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove dir if exist
rm -rf $OUTPUT_DIR

# Create dir
mkdir -p $OUTPUT_DIR

# Generate random number for
# determining how many files to create
NUM_FILES=$((RANDOM %6 + 5))

mkdir -p "$OUTPUT_DIR"

for ((i=1; i<=NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"
    
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

# See tree for files
tree $OUTPUT_DIR


aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files