#!/usr/bin/env bash

echo "== deploy S3 bucket via cfn"


STACK_NAME = "example-s3-cfn"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region eu-central-1 \
--stack-name $STACK_NAME
